//
//  Data.swift
//  EQ Playbook
//
//  Created by Yaboo Liang on 30/05/2018.
//  Copyright © 2018 Yaboo Liang. All rights reserved.
//

import Foundation

var searchResults: [String] = []

var favouritesArray: [String] = []

var titles = ["Anger",
              "Anguish",
              "Anxiety",
              "Annoyance",
              "Apathy",
              "Awe",
              "Boredom",
              "Confidence",
              "Contempt",
              "Contentment",
              "Courage",
              "Curiosity",
              "Depression",
              "Desire",
              "Disappointment",
              "Disgust",
              "Dread",
              "Ecstasy",
              "Embarrassment",
              "Empathy",
              "Envy",
              "Excitement",
              "Fear",
              "Frustration",
              "Gratitude",
              "Grief",
              "Guilt",
              "Happiness",
              "Hatred",
              "Hope",
              "Horror",
              "Hysteria",
              "Jealousy",
              "Loneliness",
              "Love",
              "Lust",
              "Outrage",
              "Pain",
              "Panic",
              "Pleasure",
              "Pride",
              "Rage",
              "Regret",
              "Resentment",
              "Sadness",
              "Saudade (missing someone)",
              "Schadenfreude",
              "Self-confidence",
              "Shame",
              "Shock",
              "Shyness",
              "Surprise",
              "Terror",
              "Trust",
              "Wonder",
              "Worry"
]

var definitions = ["Anger is an intense emotion defined as a response to a perceived provocation, the invasion of one’s boundaries, or a threat. From an evolutionary standpoint, anger servers to mobilise psychological resources in order to address the threat/invasion. Anger is directed at an individual of equal status.",
                   "Anguish can be defined as the discomfort resulting from the consideration of an overwhelming number of valid choices.",
                   "Anxiety is the dread over expected harmful events. From an evolutionary perspective, increased anxiety serves to increase vigilance to potential threats in the environment as well as increase the tendency to take proactive actions regarding such possible threats. The body often mobilises itself to meet the perceived threat: Muscles become tense, breathing is faster, and the heart beats more rapidly.",
                   "Annoyance is an unpleasant state caused when one’s regular thought process and actions are interrupted or disturbed.",
                   "Apathy is a state of indifference, or the suppression of emotions such as concern, excitement, motivation, and/or passion. It can result from one feeling they do not possess the strength to confront a challenge. /nApathy does however have positive effects and is considered a natural mechanism for coping with stress. Being able to 'shrug off' disappointments is considered an important step in helping one move on driving him/her to try other activities or pursue new goals. Apathy can also be result from one's social system hindering exploration.",
                   "Awe is the result of witnessing something surprising or impressive, but dangerous or fear-inducing. Awe is directed at objects considered to be larger and more powerful than the subject, e.g. the Great Pyramid of Giza, the Grand Canyon, or the vastness of space.",
                   "Boredom is an emotional or psychological state experienced when an individual is left without anything in particular to do, is not interested in his or her surroundings, or feels that a certain period is dull or tedious.",
                   "Confidence is the state of being certain that a hypothesis or course of action is correct.",
                   "Contempt is a mixture of disgust and anger, generally aimed at a lower status individual.",
                   "Contentment is an emotional state of satisfaction derived from one having accepted their condition, usually in disfavour of pursuing their grander ambitions.",
                   "Courage is defined as strength in the face of danger, pain, pressure, uncertainty, or intimidation.",
                   "Curiosity is used to denote the desire to investigate, gain knowledge or information, and, in an evolutionary context, is attributed as a major driving force behind human development.\n\nOne theory of curiosity (Curiosity-drive theory) states that it is a natural response to a disruption in the environment and thus of one’s cognitive process, and thus an attempt to understand the unfamiliar.\n\nA second theory (Optimal-arousal theory) justifies the presence of curiosity even in the absence of uncertain or ambiguous situations, and it dictates that one can be motivated to maintain a pleasurable sense of arousal through exploratory behaviours.",
                   "Depression is a state of low mood and aversion to activity that can affect a person's thoughts, behaviour, feelings and sense of well-being.\n\nPeople with a depressed mood can feel sad, anxious, empty, hopeless, helpless, worthless, guilty, irritable, ashamed or restless. They may lose interest in activities that were once pleasurable, experience loss of appetite or overeating, have problems concentrating, remembering details or making decisions, and may contemplate suicide.",
                   "Desire is the state of longing or hoping for a person, object or outcome.",
                   "Disappointment is the feeling of dissatisfaction resulting when expectations or hopes fail to manifest. The psychological results of disappointment vary greatly among individuals; while some recover quickly, others mire in frustration or blame, or become depressed.",
                   "Disgust is an emotional response of revulsion to something considered offensive, distasteful, or unpleasant. Many researchers have theorised that the emotion of disgust has evolved as means of protecting us from disease. Disgust appears to be triggered by objects or people who possess particular characteristics that signify disease, such as:\n\nbody products (feces, urine, vomit, sexual fluids, saliva, and mucus), spoiled foods, animals (fleas, ticks, lice, cockroaches, worms, flies, rats, and mice), hygiene (visible dirt and 'inappropriate' acts [e.g., using an unsterilised surgical instrument]), body envelope violations (blood, gore, and mutilation), death (dead bodies and organic decay) or visible signs of infection.",
                   "Dread is fear elicited when facing something perceived as both threatening and resentful.",
                   "Ecstasy is a subjective experience of one's total involvement with an object of his or her awareness. The state is characterised by a diminished awareness of other objects or the total lack of awareness of surroundings and everything around the object in question.",
                   "Embarrassment is an emotional state of intense discomfort with oneself, experienced when having a socially unacceptable act witnessed by or revealed to others. It is similar to shame, except that shame may be experienced for an act known only to oneself. Embarrassment is usually considered to be resulting from something that is merely socially unacceptable, rather than morally wrong.",
                   "Empathy means understanding a person from his or her frame of reference rather than one’s own, or vicariously experiencing that person’s feelings, perceptions, and thoughts.\n\nEmpathy does not, of itself, entail motivation to be of assistance, although it may turn into sympathy or personal distress, which may result in action.",
                   "Envy is an emotion which occurs when one lacks but desires another's perceived superior quality, achievement, or possession.",
                   "Excitement is the state of being enthusiastic over anticipated positive events.",
                   "Fear is a response to real or immediate threats, resulting in an immediate alarm reaction that mobilises the organism and triggers a set of physiological changes. These include rapid heartbeat, redirection of blood flow away from the periphery toward the gut, tensing of the muscles, and a general mobilisation of the organism to take action.",
                   "Frustration is an unpleasant response arising from the clash of an individual’s will and an obstruction preventing it from materialising.",
                   "Gratitude is a feeling of acknowledgement of a benefit that one has received. It should not be confused with being indebted, which can motivate the recipient of the aid to avoid the person who helped them, whereas gratitude can motivate the recipient to seek out and try to improve their relationship with the person who helped them.",
                   "Grief is the response to the loss of something or someone, to which or to whom a bond was formed. From an evolutionary standpoint, grief is considered to be a negative consequence of our capacity for commitment and can be justified as a motivator for one to search for the lost person.",
                   "Guilt is an emotional experience that occurs when a person realises they have compromised their own standards of conduct or have violated a moral one and bears significant responsibility for that violation. From an evolutionary perspective, guilt is considered to have helped maintain healthy relationships.",
                   "Happiness is an emotional state of well-being encompassing positive or pleasant emotions such as satisfaction or contentment.",
                   "Hatred is a deep and emotional severe dislike often associated with feelings of anger, disgust and a disposition towards hostility. In psychoanalysis, Sigmund Freud defined hate as an ego state that wishes to destroy the source of its unhappiness.",
                   "Hope is an optimistic attitude based on an expectation of positive outcomes. It is considered to require the following thought components:\n\n- goals, or having clearly defined objectives.\n\n- agency, or the individual's confidence in their ability to influence their environment.\n\n- and pathway, or the individual's confidence in their ability to determine the ways in which they could achieve their goals.",
                   "Horror is the feeling of revulsion that occurs after something frightening is experienced. It should not be confused with Terror, which is described as the feeling of dread and anticipation that precedes a horrifying experience.",
                   "Hysteria is, in colloquial terms, an act of exaggeration or emotional excess resulting from one attempting to suppress another emotion. It is a defence mechanism and used in lieu of a more rational analysis.\n\nWhile the term is used colloquially today, it has in the past been used by the medical community to refer to various mental disorders.",
                   "Jealousy is related to thoughts and feelings of insecurity, fear, concern, and anxiety over an anticipated loss of or change in status with something of great personal value, particularly in reference to a human connection. Jealousy often consists of a combination of emotions such as anger, resentment, inadequacy, helplessness and disgust.",
                   "Loneliness is a complex and usually unpleasant emotional response to isolation or lack of companionship. It typically includes anxious feelings about the lack of connectedness or communality with other beings, both in the present and extending into the future.\n\nFrom an evolutionary standpoint, loneliness can be explained as a motivator to stay close to the safety of groups.",
                   "Love refers to a complex emotion involving strong feelings of affection, attraction and personal attachment, pleasurable sensations in another's presence as well as devotion to their well-being.",
                   "Lust is an emotion or feeling of intense desire towards sex, extravagance, or power.",
                   "Outrage is a strong emotion characterised by reaction of shock, anger and indignation to a grave personal offence. The offence is perceived as violating acceptable standards of behaviour.",
                   "Pain is an unpleasant sensory and emotional experience associated with actual or potential tissue damage.",
                   "Panic is a sudden sensation of fear that overwrites normal reasoning and may include terror and confusion.",
                   "Pleasure is an encompassing term describing the broad class of mental states that humans and other animals experience as positive, enjoyable, or worth seeking.",
                   "Pride is a self-conscious emotion that occurs when a goal has been attained and one’s achievement has been recognised and approved by others. It differs from happiness, whic does not require the approval of others to be experienced.",
                   "Rage is a feeling of intense, violent, or growing anger. It is associated with the fight-or-flight response and often activated in response to a negative external cue. Rage is invoked when more rational alternatives have been exhausted.",
                   "Regret is an emotional response to remembrance of a past experience or condition that one wishes had been different.",
                   "Resentment is anger aimed at a higher status individual.",
                   "Sadness is emotional pain associated with, or encompassing feelings of disadvantage, loss, despair, grief, helplessness and disappointment. Hindering the exploration or expression of sadness during childhood can lead to difficulty coping with sadness later on.",
                   "Saudade (or missing someone) is a deep emotional state of nostalgic or profound melancholic longing for an absent something or someone that one loves. Moreover, it often carries a repressed knowledge that the object of longing might never return. A stronger form of saudade might be felt towards people and things whose whereabouts are unknown, such as a lost lover, or a family member who has gone missing, moved away, separated, or died.",
                   "Schadenfreude is pleasure derived from the misfortunes of others. People with low self-esteem have been found to be more prone to this emotion.",
                   "Self-confidence relates to certainty in one's personal judgment, ability or power. It is directly connected to one's social circle, and what one hears about themselves from others.",
                   "Shame is a painful, social emotion that can result from one's actions not meeting their own standards or the ideal social standards appropriate for the context.",
                   "Shock is an emotional response to a negative, drastic change in one's environment. Not to be confused with Surprise, which is a response to a positive event.",
                   "Shyness is the feeling of discomfort occurring when a person is in proximity to other people, especially during unfamiliar situations. It is more likely to occur in individuals who dealt with fearful experiences during their childhood.\n\nDifferentiating between introversion and shyness, introverts choose to avoid social situations because they derive no reward from them or may find them overwhelming, whereas shy people may fear such situations.",
                   "Surprise is a brief emotional state experienced as the result of an unexpected, but significant, positive event. Not to be confused with Shock, which is the response to a sudden negative event.",
                   "Terror is usually described as the feeling of dread and anticipation that precedes a horrifying experience. It should not be confused with Horror, which is the feeling of revulsion that occurs after something frightening is experienced.",
                   "Trust can be defined as the willingness of one party to rely on the actions of another and forego control over the other party's actions. Honesty, fairness and benevolence in the other party are considered to be prerequisites for trust.",
                   "Wonder is an emotion felt when perceiving something rare or unexpected, but not threatening. It can be linked with curiosity.",
                   "Worry refers to thoughts or actions that are made in an attempt to avoid anticipated potential threats. Worry arises as an attempt to anticipate all possible outcomes to a situation, or generate all possible solutions to a problem. Worry is then maintained as there are an infinite number of outcomes that can be generated, and the worrier is held in a state of worry, rather than engaging in constructive problem solving. Highly worried individuals are more likely to lack confidence in their problem-solving ability, perceive problems as threats, become easily frustrated when dealing with a problem, and be pessimistic about the outcome of their  problem-solving efforts.\n\nRefer to 'The Intolerance of Uncertainty Model (IUM) for more details."
]

var links = [
    "https://en.wikipedia.org/wiki/Anger",
    "https://en.wikipedia.org/wiki/Anguish",
    "https://en.wikipedia.org/wiki/Anxiety",
    "https://en.wikipedia.org/wiki/Annoyance",
    "https://en.wikipedia.org/wiki/Apathy",
    "https://en.wikipedia.org/wiki/Awe",
    "https://en.wikipedia.org/wiki/Boredom",
    "https://en.wikipedia.org/wiki/Confidence",
    "https://en.wikipedia.org/wiki/Contempt",
    "https://en.wikipedia.org/wiki/Contentment",
    
    "https://en.wikipedia.org/wiki/Courage",
    "https://en.wikipedia.org/wiki/Curiosity",
    "https://en.wikipedia.org/wiki/Depression",
    "https://en.wikipedia.org/wiki/Desire",
    "https://en.wikipedia.org/wiki/Disappointment",
    "https://en.wikipedia.org/wiki/Disgust",
    "https://en.wikipedia.org/wiki/Angst", // Dread
    "https://en.wikipedia.org/wiki/Ecstasy_(emotion)",
    "https://en.wikipedia.org/wiki/Embarrassment",
    "https://en.wikipedia.org/wiki/Empathy",
    
    "https://en.wikipedia.org/wiki/Envy",
    "https://en.wikipedia.org/wiki/Anticipation",
    "https://en.wikipedia.org/wiki/Fear",
    "https://en.wikipedia.org/wiki/Frustration",
    "https://en.wikipedia.org/wiki/Gratitude",
    "https://en.wikipedia.org/wiki/Grief",
    "https://en.wikipedia.org/wiki/Guilt_(emotion)",
    "https://en.wikipedia.org/wiki/Happiness",
    "https://en.wikipedia.org/wiki/Hatred",
    "https://en.wikipedia.org/wiki/Hope",
    
    "https://en.wikipedia.org/wiki/Horror_and_terror",
    "https://en.wikipedia.org/wiki/Hysteria",
    "https://en.wikipedia.org/wiki/Jealousy",
    "https://en.wikipedia.org/wiki/Loneliness",
    "https://en.wikipedia.org/wiki/Love",
    "https://en.wikipedia.org/wiki/Lust",
    "https://en.wikipedia.org/wiki/Outrage_(emotion)",
    "https://en.wikipedia.org/wiki/Pain",
    "https://en.wikipedia.org/wiki/Panic",
    "https://en.wikipedia.org/wiki/Pleasure",
    
    "https://en.wikipedia.org/wiki/Pride",
    "https://en.wikipedia.org/wiki/Rage_(emotion)",
    "https://en.wikipedia.org/wiki/Regret",
    "https://en.wikipedia.org/wiki/Resentment",
    "https://en.wikipedia.org/wiki/Sadness",
    "https://en.wikipedia.org/wiki/Saudade",
    "https://en.wikipedia.org/wiki/Schadenfreude",
    "https://en.wikipedia.org/wiki/Self-confidence",
    "https://en.wikipedia.org/wiki/Shame",
    "https://en.wikipedia.org/wiki/Acute_stress_reaction",
    
    "https://en.wikipedia.org/wiki/Shyness",
    "https://en.wikipedia.org/wiki/Surprise_(emotion)",
    "https://en.wikipedia.org/wiki/Horror_and_terror",
    "https://en.wikipedia.org/wiki/Trust_(emotion)",
    "https://en.wikipedia.org/wiki/Wonder_(emotion)",
    "https://en.wikipedia.org/wiki/Worry",
    
]

